M48
; DRILL file {KiCad (6.0.0)} date Sun Nov 20 21:00:31 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-20T21:00:31+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.0921Y-3.1792
X3.0957Y-2.0383
X5.1393Y-2.0375
X5.1393Y-3.1792
T0
M30
